pluginManagement {
	repositories {
		maven { url "https://maven.fabricmc.net/" }
		maven { url "https://maven.architectury.dev/" }
		maven { url "https://maven.minecraftforge.net/" }
		gradlePluginPortal()
	}
}

include("common")

def enabledPlatforms = providers.gradleProperty("enabled_platforms").getOrElse("fabric,forge").split(",") as Set
if (enabledPlatforms.contains("fabric")) include("fabric")
if (enabledPlatforms.contains("forge")) include("forge")

rootProject.name = "fastitems"

